name: Blog

on:
  push:
    branches:
      - main
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all|write-all
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/checkout@v3
        with:
          repository: Yidadaa/Issue-Blog-With-Github-Action
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://raw.githubusercontent.com/junqi-lu/junqi-lu.github.io/main/.github/workflows/cv.md -O ./src/cv.md
          wget https://raw.githubusercontent.com/junqi-lu/junqi-lu.github.io/main/.github/workflows/custom.js -O ./src/.vuepress/custom.js
          pnpm i 
          pnpm action
          pnpm build
          pnpm run deploy
